schemaVersion: 2
name: release-arm64-jvm
registry:
  repository: 127.0.0.1:5000/nanofaas
  tag: v0.22.0-arm64-jvm
controlPlane:
  modules:
  - async-queue
  - autoscaler
  - build-metadata
  - concurrency-control
  - k8s-deployment-provider
  - offload
  - runtime-config
  - sync-queue
  build:
    mode: jvm
    variant: jvm-g1-c2
  jvm:
    args:
    - -XX:+UseG1GC
  container:
    image: control-plane
functions:
- name: binary-envelope
  sdk: java
  build:
    mode: jvm
  jvm:
    args:
    - -XX:+UseG1GC
  container:
    image: java-binary-envelope
- name: figlet
  sdk: java
  build:
    mode: jvm
  jvm:
    args:
    - -XX:+UseG1GC
  container:
    image: java-figlet
- name: handler-envelope
  sdk: java
  build:
    mode: jvm
  jvm:
    args:
    - -XX:+UseG1GC
  container:
    image: java-handler-envelope
- name: json-transform
  sdk: java
  build:
    mode: jvm
  jvm:
    args:
    - -XX:+UseG1GC
  container:
    image: java-json-transform
- name: qr-code
  sdk: java
  build:
    mode: jvm
  jvm:
    args:
    - -XX:+UseG1GC
  container:
    image: java-qr-code
- name: roman-numeral
  sdk: java
  build:
    mode: jvm
  jvm:
    args:
    - -XX:+UseG1GC
  container:
    image: java-roman-numeral
- name: word-stats
  sdk: java
  build:
    mode: jvm
  jvm:
    args:
    - -XX:+UseG1GC
  container:
    image: java-word-stats
services:
- name: warm-echo
  sdk: java
  build:
    mode: jvm
  jvm:
    args:
    - -XX:+UseG1GC
  container:
    image: java-warm-echo
